### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by jeena** [onedayitwillmake/RealtimeMultiplayerNodeJs#7]
Hi,

how are you supposed to start the demo? The documentation just says: 'Browse to "/DemoHelloWorld.html"' but on which server or port or just with file://? I tried

http://localhost/path/to/DemoHelloWorld.html (via my local Apache)
file:///path/to//DemoHelloWorld.html
http://example.com/path/to//DemoHelloWorld.html (Apache on the internet)
http://localhost:8081/DemoHelloWorld.html (Port from js/model/Constants.js)
http://example.com:8081/DemoHelloWorld.html (Port from js/model/Constants.js)

The description suggests that this would be perfect for what we try to do (a multiplayer server/client game with node in the browser) but it seems not to matter what I try to get the demo up and running (I even tried it as root as one other guy suggested), either nothing happens or I get the error:

```
Lala:game jeena$ sudo node js/DemoHelloWorld/server.js
Password:
7 Jun 13:59:08 - socket.io ready - accepting connections
7 Jun 13:59:29 - Initializing client with transport "websocket"
7 Jun 13:59:29 - WebSocket connection invalid or Origin not verified
7 Jun 13:59:34 - Initializing client with transport "xhr-polling"

/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/transports/xhr-polling.js:119
    res.setHeader('Content-Type', 'text/plain; charset=UTF-8');
        ^
TypeError: Object #<a ServerResponse> has no method 'setHeader'
    at Polling._write (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/transports/xhr-polling.js:119:9)
    at Polling._payload (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/client.js:167:28)
    at Polling._onConnect (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/transports/xhr-polling.js:59:12)
    at Polling.Client (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/client.js:49:8)
    at new Polling (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/transports/xhr-polling.js:24:10)
    at Listener._onConnection (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/listener.js:223:66)
    at Listener.check (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/listener.js:142:12)
    at Server.<anonymous> (/Users/jeena/game/js/lib/Socket.IO-node/lib/socket.io/listener.js:68:14)
    at Server.emit (events:27:15)
    at HTTPParser.onIncoming (http:83Lala:game jeena$ sudo node js/DemoHelloWorld/server.js
```

**Comment by fyyyyy** [comment]
worked for me :+1:
